stages:
  - build
  - coverage

rust-latest:
  stage: build
  image: rust:latest
  script:
    - cargo build --verbose
    - cargo test --verbose

rust-nightly:
  stage: build
  image: rustlang/rust:nightly
  script:
    - cargo build --verbose
    - cargo test --verbose
  allow_failure: true

coverage:
  stage: coverage
  image: xd009642/tarpaulin
  script:
    - rustup toolchain install nightly
    - cargo tarpaulin --doc --lib
